/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jamff_ndk_Encrypt */

#ifndef _Included_com_jamff_ndk_Encrypt
#define _Included_com_jamff_ndk_Encrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jamff_ndk_Encrypt
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jamff_ndk_Encrypt_encrypt
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_jamff_ndk_Encrypt
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jamff_ndk_Encrypt_decrypt
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
